# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: mac

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs:
      - job: Restore
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'restore'
              projects: '**/WebApp.csproj'

          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: '**/WebApp.csproj'
              arguments: '--configuration $(buildConfiguration)'

      - job: Test
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              projects: '**/*UnitTest*.csproj'
              
  - stage: Publish
    jobs:
      - job:
        steps:
          - task: DotNetCoreCLI@2
            displayName: Create WebApp package (.zip)
            inputs:
              command: 'publish'
              publishWebProjects: true
              arguments: '-- configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
              zipAfterPublish: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'